name: ğŸ•µğŸ½â€â™€ï¸ RunParsersTest

on:
  workflow_dispatch:
    inputs:
      cmdParams:
        description: 'cmd parameters'
        required: true
        default: '-parser markas'
        type: string
jobs:
  testGenerateXMLFeeds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run parsers & update xml feeds
      run: |
        echo python updateFeeds.py ${{ github.event.inputs.cmdParams }} -meta -feed -json -index
        python updateFeeds.py ${{ github.event.inputs.cmdParams }} -meta -feed -json -index
    - name: Test files in github pages
      run: |
        python tests/test_ghpages.py
    - name: Upload github pages /docs/ artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: github-pages-docs
        path: docs/
